name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

  ansible:
    name: Configure and Deploy Application with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Install dependencies for dynamic inventory
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install boto3 botocore ansible amazon.aws

      - name: Create dynamic inventory file
        run: |
          echo "
          plugin: amazon.aws.aws_ec2
          regions:
            - us-east-1
          filters:
            instance-state-name: running
          keyed_groups:
            - key: tags.Name
          hostnames:
            - public-ip-address
          compose:
            ansible_user: ec2-user  # Add ansible_user for all hosts
          " > aws_ec2.yml

      - name: Test dynamic inventory
        run: ansible-inventory -i aws_ec2.yml --list

      - name: Execute Ansible Playbook using dynamic inventory
        run: |
          ansible-playbook -i aws_ec2.yml deploy.yml --key-file ~/.ssh/id_rsa
