name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure with Terraform and Deploy with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan and Save Outputs
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          terraform output -json > tf_outputs.json

      - name: Generate Inventory File Using Python Script
        run: python3 generate_inventory.py

      - name: Add Host Key to Known Hosts (Avoid Verification Error)
        run: |
          ssh-keyscan -H $(awk '/\[web\]/{getline; print $1}' inventory.ini) >> ~/.ssh/known_hosts

      - name: Add SSH Key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Execute Ansible Playbook using Inventory File
        run: |
          ansible-playbook -i inventory.ini deploy.yml --key-file ~/.ssh/id_rsa
