name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

  ansible:
    name: Configure and Deploy Application with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible

      - name: Execute Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini deploy.yml --key-file ~/.ssh/id_rsa
