name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Apply Terraform Plan and Save Outputs
      - name: Apply Terraform Plan and Save Outputs
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          terraform output -json > tf_outputs.json

      # Step 6: Install Python dependencies (if needed)
      - name: Install Python dependencies (if required)
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      # Step 7: Generate Inventory File Using Python Script
      - name: Generate Inventory File Using Python
        run: python3 generate_inventory.py

      # Step 8: Add SSH Key for Ansible
      - name: Add SSH key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Step 9: Install Ansible on Runner
      - name: Install Ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible

      # Step 10: Execute Ansible Playbook using Inventory File
      - name: Execute Ansible Playbook using Inventory File
        run: |
          ansible-playbook -i inventory.ini deploy.yml --key-file ~/.ssh/id_rsa
