name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure with Terraform and Deploy with Ansible
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3 (New): Build and Push Docker Image to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pythonapp:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pythonapp:latest

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 5: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 6: Apply Terraform Plan and Save Outputs
      - name: Apply Terraform Plan and Save Outputs
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          terraform output -json > tf_outputs.json

      # Step 7: Generate Inventory File Using Python Script
      - name: Generate Inventory File Using Python Script
        run: python3 generate_inventory.py

      # Step 8: Add SSH Key for Ansible
      - name: Add SSH Key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Step 9: Install Ansible on Runner
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      # Step 10: Execute Ansible Playbook using Inventory File
      - name: Execute Ansible Playbook using Inventory File
        run: |
          ansible-playbook -i inventory.ini deploy.yml
